name = "Rohan"
print(name[0])
print(name[1])
print(name[2])
print(name[3])
print(name[4])
print(name)
print(len(name))
print(name.lower())
print(name.upper())
print(name.replace("an","it"))
print(name.isalpha())
print(name.isnumeric())
#string slicing
print(name[0:3])